backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)


media_folder: "public/images"
public_folder: "/images"



collections:
    - name: "project" # Used in routes, e.g., /admin/collections/blog
      label: "project" # Used in the UI
      folder: "projects" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Description",name: "desc",widget: "markdown"}
        - {label: "Project Date", name: "date", widget: "datetime"}
        - {label: "Project Image", name: "image", widget: "image"}
        - {label: "Github Link", name: "githubLink", widget: "string", required: false}
        - {label: "Live Link", name: "liveLink", widget: "string", required: false}
        - {label: "Tags", name: "tags", widget: "string"}